# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
    branches:
        include:
        - master
    paths:
        include:
        - src/Front*

pool:
  vmImage: 'ubuntu-latest'

variables:
    - group: shsdol

steps:
- task: Docker@2
  inputs:
    repository: 'pastafyfront'
    command: 'build'
    Dockerfile: '**/DockerfileFront'
    addPipelineData: false

- task: ECRPushImage@1
  inputs:
    awsCredentials: 'AWS'
    regionName: 'us-east-1'
    imageSource: 'imagename'
    sourceImageName: 'pastafyfront'
    sourceImageTag: '$(Build.BuildId)'
    repositoryName: 'pastafyfront'
    logResponse: true

- task: ECRPushImage@1
  inputs:
    awsCredentials: 'AWS'
    regionName: 'us-east-1'
    imageSource: 'imagename'
    sourceImageName: 'pastafyfront'
    sourceImageTag: '$(Build.BuildId)'
    repositoryName: 'pastafyfront'
    logResponse: true
    